parameters:
#    imv_user.example.class: Imv\UserBundle\Example

services:
#    imv_user.example:
#        class: %imv_user.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
