<?php

namespace Imv\CoreBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * WordListRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class WordListRepository extends EntityRepository
{
}
